openai:
  api_version: "2024-02-15-preview"
  engine: "gpt-4"
  temperature: 0.3
  max_tokens: 1000
  max_concurrent_requests: 5
  batch_size: 10

database:
  metrics_table: "fact_social_media_ai_metrics"
  details_table: "dim_social_media_ai_details"
  secret_arn: "arn:aws:secretsmanager:eu-central-1:471112963254:secret:DP-gpt4o-mini-batch-1alaDL"
  batch_limit: 100

prompts:
  analyze: |
    You are a social media analytics expert. Analyze the following social media post and provide metrics and insights.

    Format your response as a JSON object with the following structure:
    {format}

    Input Data:
    {input_data}

    Analyze the input data and provide metrics and details in the format specified above. For metrics, provide scores between 0 and 1.
    For details, provide clear explanations and insights. Make sure all fields in the format are included in your response.
    Your response must be valid JSON.

logging:
  level: INFO
  retention_days: 14
