AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Social Media Analytics Enrichment Lambda Functions

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  OpenAISecretName:
    Type: String
    Default: ptdata/openai
    Description: Name of the secret containing OpenAI credentials

  LogRetentionDays:
    Type: Number
    Default: "14"
    Description: CloudWatch Logs retention period in days

Globals:
  Function:
    Timeout: 900 # 15 minutes
    MemorySize: 1024
    Runtime: python3.11
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        OPENAI_SECRET_NAME: !Ref OpenAISecretName
        PYTHONPATH: /var/task:/var/task/src
    Tags:
      Environment: !Ref Environment
      Service: social-media-enrichment

Resources:
  # UserNeedsFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: .
  #     Handler: handler.lambda_handler
  #     Description: Processes social media data for user needs analysis
  #     Events:
  #       Schedule:
  #         Type: Schedule
  #         Properties:
  #           Schedule: rate(30 minutes)
  #           Input:
  #             path: /user_needs
  #             queryStringParameters:
  #               max_records: "10000"
  #     Policies:
  #       - Version: "2012-10-17"
  #         Statement:
  #           - Effect: Allow
  #             Action:
  #               - secretsmanager:GetSecretValue
  #               - glue:*
  #               - s3:*
  #             Resource: "*"

  ModelInferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.lambda_handler
      Description: Generic function for all model types via HTTP API
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{model}
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - glue:*
                - s3:*
              Resource: "*"

Outputs:
  ModelInferenceApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
