AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Social Media Analytics Enrichment Lambda Functions

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  OpenAISecretName:
    Type: String
    Default: ptdata/openai
    Description: Name of the secret containing OpenAI credentials

  LogRetentionDays:
    Type: Number
    Default: "14"
    Description: CloudWatch Logs retention period in days

Globals:
  Function:
    Timeout: 900 # 15 minutes
    MemorySize: 1024
    Runtime: python3.11
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        OPENAI_SECRET_NAME: !Ref OpenAISecretName
        PYTHONPATH: /var/task:/var/task/src
    Tags:
      Environment: !Ref Environment
      Service: social-media-enrichment

Resources:
  SentimentAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.lambda_handler
      Description: Processes social media data for sentiment analysis
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${OpenAISecretName}-*"
            - Effect: Allow
              Action:
                - glue:*
                - s3:*
              Resource: "*"
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /sentiment
            Method: POST
            PayloadFormatVersion: "2.0"
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Name: SentimentAnalysisSchedule
            Description: Run sentiment analysis every hour
            Enabled: true
      LoggingConfig:
        LogGroup:
          RetentionInDays: !Ref LogRetentionDays

Outputs:
  SentimentAnalysisApi:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/sentiment
