aws:
  region: eu-central-1
  output: s3://aws-orf-social-media-analytics/dev/gold/
  db:
    primary: ["id", "post_key"]
    source:
      - database: dev_gold
        table: fact_social_media_reaction_post
        query:
          template: "SELECT * FROM {database}.{table} WHERE date_key >= {start_date} ORDER BY {order_by} DESC LIMIT {limit}"
          params:
            start_date: "CURRENT_DATE - INTERVAL '1 days'"
            order_by: date_key
      - database: dev_gold
        table: dim_post_details
        query:
          template: "SELECT * FROM {database}.{table} WHERE date_key >= {start_date} ORDER BY {order_by} DESC LIMIT {limit}"
          params:
            start_date: "CURRENT_DATE - INTERVAL '1 days'"
            order_by: date_key
    target:
      - database: dev_gold
        table: fact_social_media_ai
        query:
          template: "INSERT INTO {database}.{table} ({columns}) VALUES ({data})"
          params:
            data : 
            columns: 
      - database: dev_gold
        table: dim_social_media_ai
        query:
          template: "INSERT INTO {database}.{table} ({columns}) VALUES ({data})"
          params:
            columns: 

openai:
  api_key: ${oc.env:OPENAI_API_KEY}
  api_base: ${oc.env:OPENAI_API_BASE}
  api_version: 2024-10-01-preview
  engine: gpt-4o-mini
  max_workers: 10

logging:
  level: INFO
  handlers:
    file:
      enabled: true
      level: DEBUG
      filename: "app.log"