connector:
  source:
    tables:
      - database: prod_gold
        table: dim_post_details
        datetime_field: last_update_time
        index_field: post_key
    time_filter_hours: 10

  target:
    database: dev_gold
    table: social_media_needs
    datetime_field: written_at
    index_field: post_key
    location: s3://aws-orf-social-media-analytics/dev/gold/ai/social_media_needs
    partition_by: month

inference:
  workers: 20
  response_format: user_needs
  max_tokens: 16384
  include_fields:
    - post_message
