aws:
  output: "s3://aws-orf-social-media-analytics/dev/gold/"
  primary: ["id", "post_key", "channel_key", "date_key"]

  db:
    sources: 
      - database: "dev_gold"
        table: "fact_social_media_reaction_post"
      - database: "dev_gold"
        table: "dim_post_details"
    targets:
      - database: "dev_gold"
        table: "dim_social_media_ai_details"
      - database: "dev_gold"
        table: "fact_social_media_ai_metrics"

  client:
openai:
  max_workers: 5
  client:
    api_version: "2024-10-01-preview"
    engine: "gpt-4o-mini"

  model:
    temperature: 0.3
    max_tokens: 1000
  

  prompts:
    system: |
      You are a social media analytics expert. Analyze the following social media post and provide metrics and insights.

      Analyze the input data and provide metrics and details in the format specified above. For metrics, provide scores between 0 and 1.
      For details, provide clear explanations and insights. Make sure all fields in the format are included in your response.
      Your response must be valid JSON.

      Format your response as a JSON object with the following structure:
      {0}
    user: |
      Input data:
      {0}

logging:
  version: 1
  disable_existing_loggers: true
  formatters:
    standard:
      format: "%(asctime)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    file:
      class: logging.FileHandler
      level: INFO
      formatter: standard
      filename: enrichment.log
      mode: w
  root:
    level: INFO
    handlers: [file]