name: Continuous Deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.py'
      - 'src/**'
      - 'pyproject.toml'
      - 'Dockerfile'
      - 'template.yaml'
      - 'config/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::471112963254:role/GitHubActionsRole
          aws-region: eu-central-1
          role-session-name: main
          
      - name: Deploy to AWS
        run: |
          aws cloudformation package --template-file template.yaml --s3-bucket ptdata-lambda-artifacts --output-template-file packaged.yaml
          aws cloudformation deploy --template-file packaged.yaml --stack-name ptdata-social-media-enrichment --capabilities CAPABILITY_IAM
